# Generated by Django 6.0.4 on 2026-04-27 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(default='', max_length=100)),
                ('dept', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('sem', models.IntegerField()),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], max_length=10)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=30)),
                ('colour', models.CharField(default='#c084f5', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='subject/')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.FloatField()),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.profile')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.TimeField()),
                ('date', models.DateField()),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('deadline', models.DateField()),
                ('max_marks', models.FloatField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.profile')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('video_url', models.URLField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_enrolled', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.profile')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.assignment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.profile')),
            ],
        ),
    ]
