# Generated by Django 6.0.4 on 2026-05-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilmsapp', '0002_alter_profile_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
