# Generated by Django 6.0.4 on 2026-05-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilmsapp', '0004_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
