# Generated by Django 6.0.4 on 2026-05-08 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilmsapp', '0006_rename_marks_result_obtained_marks_remove_result_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.profile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.subject')),
            ],
        ),
    ]
