# Generated by Django 6.0.4 on 2026-05-10 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilmsapp', '0007_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('color', models.CharField(default='#c084f5', max_length=10)),
                ('event_type', models.CharField(choices=[('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Project', 'Project'), ('Holiday', 'Holiday')], max_length=25)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilmsapp.subject')),
            ],
        ),
    ]
