# Generated by Django 6.0.4 on 2026-05-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilmsapp', '0008_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
