# Generated by Django 6.0.4 on 2026-05-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilmsapp', '0009_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
