# Generated by Django 6.0.4 on 2026-06-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilmsapp', '0011_assignment_assignment_file_assignment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_marks',
            field=models.FloatField(default=10),
        ),
    ]
