# Generated by Django 6.0.4 on 2026-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unilmsapp', '0012_assignment_max_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
